{{- if and .Values.adminApiKey.enabled (not .Values.adminApiKey.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pii-shield.fullname" . }}-admin
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "pii-shield.name" . }}
    helm.sh/chart: {{ include "pii-shield.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  {{ .Values.adminApiKey.keyName }}: {{ .Values.adminApiKey.value | quote }}
{{- end }}
