{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "pii-shield.fullname" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "pii-shield.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- with .Values.serviceMonitor.additionalLabels }}
{{ toYaml . | indent 2 }}
{{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "pii-shield.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
  {{- if .Values.serviceMonitor.namespace }}
  namespaceSelector:
    matchNames:
      - {{ .Values.serviceMonitor.namespace }}
  {{- end }}
{{- end }}
