{{- if .Values.ui.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pii-shield.fullname" . }}-ui
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "pii-shield.name" . }}
    helm.sh/chart: {{ include "pii-shield.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "pii-shield.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: ui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "pii-shield.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: ui
      {{- if .Values.ui.podAnnotations }}
      annotations:
{{ toYaml .Values.ui.podAnnotations | indent 8 }}
      {{- end }}
    spec:
      containers:
        - name: pii-shield-ui
          image: "{{ default .Values.image.repository .Values.ui.image.repository }}:{{ default .Values.image.tag .Values.ui.image.tag }}"
          imagePullPolicy: {{ default .Values.image.pullPolicy .Values.ui.image.pullPolicy }}
          command: ["python", "-m", "http.server", "8080", "-d", "/app/ui"]
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: ui-config
              mountPath: /app/ui/config.js
              subPath: config.js
          resources:
{{ toYaml .Values.ui.resources | indent 12 }}
      volumes:
        - name: ui-config
          configMap:
            name: {{ include "pii-shield.fullname" . }}-ui
      {{- if kindIs "map" .Values.ui.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.ui.nodeSelector | indent 8 }}
      {{- end }}
      {{- if kindIs "map" .Values.ui.affinity }}
      affinity:
{{ toYaml .Values.ui.affinity | indent 8 }}
      {{- end }}
      {{- if kindIs "map" .Values.ui.tolerations }}
      tolerations:
{{ toYaml .Values.ui.tolerations | indent 8 }}
      {{- end }}
{{- end }}
